### ISSUE TITLE
Investigate Usage of Hunter Groups with Profile Apply

### ISSUE THREAD

**Issue by ColonelPanicks** [openflighthpc/flight-profile#48]
A useful integration option would be that `profile` can determine the `identity` to apply to a node from its primary group in `hunter`

Some initial thoughts on this:
- `apply` flag/option to autodetect the identity type
  - Some verification to determine whether the group matches an available identity in the selected cluster type
- Stretch/additional functionality - the ability to `autoapply` to all hunted nodes, selecting all their appropriate identities from the list

**Comment by Womblue** [comment]
Implemented as of #119
