### ISSUE TITLE
Include IP in Ansible Inventory File in Hunter Mode

### ISSUE THREAD

**Issue by ColonelPanicks** [openflighthpc/flight-profile#63]
Currently ansible inventories are generated with the hunter hostname (translated from the label) such that with the following hunter list:
```
┌──────────┬────────┬────────────────────────────────┬─────────────┬────────────┐
│ ID       │ Label  │ Hostname                       │ IP          │ Groups     │
├──────────┼────────┼────────────────────────────────┼─────────────┼────────────┤
│ 320a5701 │ login1 │ hunterspeedup-login1.novalocal │ 10.50.1.87  │            │
│ 320a1701 │ node01 │ hunterspeedup-node-1.novalocal │ 10.50.1.23  │ nodes, all │
└──────────┴────────┴────────────────────────────────┴─────────────┴────────────┘
```

It would create an ansible inventory that looks like
```
[login]
hunterspeedup-login1.novalocal

[compute]
hunterspeedup-node-1.novalocal
```

Which works absolutely fine in the context of the various cluster types when applying to a login node (itself) first because the playbook adds hunter nodes to `/etc/hosts` so DNS works for the non-self nodes. However, this hits the issue that when adding a new node we aren't able to resolve the hostname upfront and the playbook fails immediately. 

A proposal to fix this is that we add the IP address known to hunter to the inventory file as well, this will allow resolution and cluster setup to continue (and means we can have a proper "add node to an existing cluster" workflow). The inventory file for the above hunter list would then look like the following:
```
[login]
hunterspeedup-login1.novalocal ansible_host=10.50.1.87

[compute]
hunterspeedup-node-1.novalocal ansible_host=10.50.1.23
```

**Comment by Womblue** [comment]
Fixed in #64
