### ISSUE TITLE
Improve Multi-Node Apply

### ISSUE THREAD

**Issue by ColonelPanicks** [openflighthpc/flight-profile#80]
## Issue Overview

Applying to 32 compute nodes at once creates a massive load on the host server and deployment grinds to a halt due to the `ansible-playbook` command being run for each node to be configured.

## Considerations

Ansible is usually run on multiple nodes at once and that would significantly reduce the load. Some of the problems to address with using this method is:
1. Separating stdout on a per-node basis (likely to be something addressed in `flight-profile` so the `view` command can still work) 
2. Handling multiple nodes being handed through to the Ansible run script

## Addressing the Considerations

1. Separating Stdout 
      - Ansible allows output to be written to a directory in separate log files, this can be achieved with the following environment variables:
          - `ANSIBLE_LOG_FOLDER=/PATH/TO/OUTPUT/`: Set the directory to create log files in (this directory must exist or ansible just won't log anything anywhere) 
          - `ANSIBLE_STDOUT_CALLBACK=log_plays`: Redirect the standard output to the log file path directory
          - The above means that _nothing_ is printed to stdout of the command, this likely means `view` would need to be restructured to handle this
          - Additionally it does not look possible for the filenames to be changed so we may need to approach the separation of the "stages" of a profile run (the pre, main, post bits)
              - We could create directories for each stage + date, handling the data classification via `ANSIBLE_LOG_FOLDER` changing between each run command
              - Alternatively, we could add some notes into the logfiles as ansible appends to the logfile for the nodename
2. Handling Multiple Nodes 
    - Currently we have `$NODE` passed through and the run scripts within the playbooks do `--limit $NODE`, for handling multiple nodes at once we'll have to think about how we can hand over all the individual nodenames
    - Perhaps `$NODES` being a space separated list of nodenames which the scripts can then handle separating/using how they wish?)

## To Do

- [ ] Add ansible logging vars to env of `apply` & `remove`
- [ ] Update `view` to work with new logging method
- [ ] Update how multiple nodes are handed to the commands of a `type` (probably pairs well with the new [expanded range options](https://github.com/openflighthpc/flight-profile/pull/67))
- [ ] Update our playbooks to use the new passing of nodes from above
- [ ] Significant testing to ensure playbooks work well with this new style of usage & that logging in `view` is as expected

**Comment by VoxSecundus** [comment]
Resolved in https://github.com/openflighthpc/flight-profile/pull/96.
